### ISSUE TITLE
Coc.nvim tsserver along with vim-visual-multi has issue.

### ISSUE THREAD

**Issue by subev** [mg979/vim-visual-multi#75]
When I try to enter vim-visual-multi edit mode I end up with bunch of exceptions.
The highlight of visual multi also looks weird. This happens sometimes after I do bunch of motions and commands (e.g. yank then paste, change and let's say delete a word few times) something always goes wrong. Or it might crash initially, I am not sure what exactly goes wrong but it feels like the two plugins are incompatible.
Here is how the exceptions look like.
![vim-visual-multi](https://user-images.githubusercontent.com/1330872/63808103-db337180-c927-11e9-9ef7-6e63847f18d7.gif)
Could you suggest some work around? Did I do something wrong?

**Comment by mg979** [comment]
Edit mode would be insert mode? Those don't look like VM errors, maybe that plugin tries to display some popup or info as soon as it enters insert mode and it causes errors for some reason.

A possible solution in your case, if there's a way to disable temporarily that plugin, is to do it before VM starts, and enable it again after it ends. Read `:help vm-faq-functions`.
I'd try this approach first, because a workaround on my part requires some work and testing with a plugin I'm not using.

Part of the issue, on VM side, could be that currently VM controls also the main cursor, that is `setline()` is called also on the main cursor, this ensures that all cursors write the same text, but maybe it can cause some incompatibilities. I could try to use `noautocommand` for insert mode, but I currently rely on autocommands to update text, I'm not sure if it can be done without autocommands but I can try. But please try the approach above, thanks. If there's a way to turn the plugin off, or temporarily disable logs/popups/whatever, it should work.

**Comment by subev** [comment]
I finally understood where this is coming from, it is because of the error signs column at the beginning. Sadly even when I disable the coc.vim addon with ':CoCDisable' it does not hide the column with errors it has already reported.
Will update here if I find a work-around.

**Comment by subev** [comment]
I tried couple of times, before I post this, `:CoCDisable` and then `:CoCEnable`, it works only if I do it manually before open the file for the first time (if I clear the buffer and open the file it works too). I assume it might be some mappings that happen on BufEnter.

**Comment by mg979** [comment]
Output of `:VMDebug` when it doesn't work?
Can you post the coc.nvim configuration + coc extensions you're using, and a test file where it's not working? If I can reproduce it, maybe I can understand what's going on, and if I can do something about it in VM.

**Comment by subev** [comment]
VMDebug:
```
b24: Overwritten imap: <C-b> (I CtrlB)  ->  <C-R>=AutoPairsBackInsert()<CR>
b24: Overwritten imap: <C-e> (I CtrlE)  ->  <C-R>=AutoPairsFastWrap()<CR>
b24: Overwritten imap: <CR> (I Return)  ->  <SID>AutoPairsOldCRWrapper73<SID>AutoPairsReturn
b24: Overwritten imap: <BS> (I BS)  ->  <C-R>=AutoPairsDelete()<CR> 
```

Tonight I will try to provide a reproducing setup.

**Comment by subev** [comment]
Alright, I stripped out everything out of the .vimrc except the vim-visual-multi and coc.nvim.

Here is the .vimrc file: https://gist.github.com/subev/b93d78bfac7b553e80f8f65a637709d7
And example file:  https://gist.github.com/subev/e99a50d3566f91063e4c7c9e9a9e00ac

Make few selections targeting the `.metrics` text which have the warning sign in the sign column then press 'c', you should then see the errors.

Here is how it looks on my side:
![visual-multi](https://user-images.githubusercontent.com/1330872/70277019-304e1180-17ba-11ea-99cf-d31dfa9c93c6.gif)
P.S. Lol this video is super slow to watch as a gif ¯\_(ツ)_/¯
Thank you in advance, much appreciated!

**Comment by mg979** [comment]
I don't have these errors in nvim (0.4.3) or in vim 8.0:

![Imgur](https://i.imgur.com/p7Sjmyi.gif)

But I have them in vim 8.1, so it's some new vim bug. Even if I disable `signcolumn` I still get those errors. It's triggered by this function I'm using at some point, to get the character at position.

```vim
fun! s:Funcs.char_at_pos(l, c) abort
    return matchstr(getline(a:l), '\%' . a:c . 'c.')
endfun
```

At the moment I don't know what to do about it. You can use nvim if you need this setup.

This is the vimrc I used for the test:

```vim
if &compatible
  set nocompatible
endif

set runtimepath=$VIMRUNTIME     " turn off user scripts, https://github.com/igrigorik/vimgolf/issues/129
set packpath=

set runtimepath+=~/.vim/plugged/coc.nvim
set runtimepath+=~/.vim/plugged/vim-visual-multi
let g:coc_global_extensions = ['coc-css']

"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" debug
"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""

command! -nargs=+ -complete=command Output  call s:output(<f-args>)
cnoreabbrev oo     Output

fun! s:output(...) "{{{2
  "
  " Output the result of the Ex command into a split scratch buffer.
  "
  let cmd = join(a:000, ' ')
  let output = cmd[0:0] == '!' ? system(cmd[1:]) : execute(cmd, 'silent!')
  if empty(output)
    ErrorMsg "no output"
  else
    new
    setlocal buftype=nofile bufhidden=wipe noswapfile nobuflisted wrap
    nnoremap <buffer><nowait><silent> q :bwipe!<cr>
    silent! put! =output
    1d _
    let &l:statusline = '%#TablineSel# ' . cmd . ' %#TablineFill#'
    setlocal nomodified
  endif
endfunction

"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" settings
"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""

set scrolloff=2                 " keep 2 lines when scrolling
set autoindent                  " set auto-indenting on for programming
set showcmd                     " display incomplete commands
set ruler                       " show the current row and column
set incsearch                   " do incremental searching
set ignorecase                  " ignore case when searching
set smartcase                   " no ignorecase if Uppercase char present
set visualbell t_vb=            " turn off error beep/flash
set novisualbell                " turn off visual bell
set backspace=indent,eol,start  " make that backspace key work the way it should
set t_ut=                       " use color scheme background in shell output
syntax on                       " turn syntax highlighting on by default
filetype on                     " detect type of file
filetype indent on              " load indent file for specific file type

set nobackup                    " do not keep a backup file
set noswapfile
set mouse=a
set ttimeout
set tm=3000 ttm=10

" vim: et:ts=2:sts=2:sw=2:tw=79
```

**Comment by mg979** [comment]
Or maybe, rather than a bug, since it's only happening with coc enabled, it could be some bad interaction with the new vim popup feature.

**Comment by mg979** [comment]
I did some more testing and I found out that it's some interaction between coc (or maybe the extension) and vim 8.1, and nothing I can do about it. Basically, even outside of VM, when coc (typescript) is enabled, the function `byte2line()` returns `-1` (wrong) for positions after the third line (where the first error is). This doesn't happen in vim 8.0 or nvim.

So it's either a bug in vim 8.1, or in coc, or its extension, but I think vim 8.1 is to blame here.

**Comment by subev** [comment]
I spend the whole day migrating to nvim. Now that I know there is a way to use those two outstanding productivity plugins I should have them!
Hope this vim issue will be noticed and fixed in the future. Can we log some issue so the team is aware? 

Thanks for your help!

**Comment by mg979** [comment]
This seems fixed in the latest vim, so I'm closing it.

**Comment by jackieli-tes** [comment]
I'm getting this again in latest neovim using coc.nvim + vim-visual-multi together.

nvim 0.6.1
coc.nvim 7d6a95e4 commit on 2022-04-05
vim-visual-multi 4fcd3797 commit from 2022-03-25

It still appears to be the floating window trying to display and triggers the error.


https://user-images.githubusercontent.com/64778297/162164728-92866b15-16a6-481c-acf9-bc60e8d393d0.mp4

in the above I had:

1. move to `err`
2. `<A-N>` a few times to select all occurrences of `err`
3. `Tab` to switch to normal mode
4. `ea` to append
5. `<C-space>` to bring up completion menu from coc.nvim
6. select anything and press `<C-Y>`
7. error message appears
8. press `<esc>` to get out of insert mode
9. error message appears

**Comment by jackieli-tes** [comment]
Currently using the following workaround seems to be ok:

```
function! MyVmStart()
  execute 'CocDisable'
endfunction
function! MyVmExit()
  execute 'CocEnable'
endfunction
autocmd User visual_multi_start   call MyVmStart()
autocmd User visual_multi_exit    call MyVmExit()
```

**Comment by mg979** [comment]
@jackieli-tes try again with current master.

**Comment by jackieli-tes** [comment]
@mg979  dude it works! thanks a lot!
